"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { marked } from "marked";
import Navigation from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useAuth } from "@/contexts/AuthContext";
import AuthModal from "@/components/AuthModal";
import { PDF_BASE_CSS } from "@/lib/pdf-base";
import { validateTheme } from "@/lib/theme-schema";

// Interface matching API response
interface ThemeData {
  _id: string;
  name: string;
  description: string;
  longDescription?: string;
  css: string;
  preview: string;
  tags: string[];
  featured: boolean;
  downloads: number;
  ratingSum: number;
  ratingCount: number;
  author: {
    _id: string;
    username: string;
    verified?: boolean;
  };
  createdAt: string;
}

const PREVIEW_CONTENT = `# Sample Document

<p class="subtitle">This is how your document will look with this theme</p>

---

## Getting Started

This is a preview of the theme's styling. The actual content is from your Markdown editor.

### Typography

Regular paragraph text with **bold** and *italic* formatting. Here's some \`inline code\` as well.

> "Design is not just what it looks like and feels like. Design is how it works."
> — Steve Jobs

### Code Block

\`\`\`javascript
const theme = {
  name: "Example Theme",
  styles: "beautiful",
  ready: true
};
\`\`\`

### Sample Table

| Feature | Status | Notes |
|---------|--------|-------|
| Typography | ✅ Ready | Beautiful fonts |
| Colors | ✅ Ready | Consistent palette |
| Layout | ✅ Ready | Print-optimized |

<div class="callout callout-info">
<strong>Note:</strong> This theme is optimized for both screen preview and PDF export.
</div>

### Badges & Labels

<span class="badge badge-primary">Primary</span>
<span class="badge badge-success">Success</span>
<span class="badge badge-warning">Warning</span>

---

*Preview generated by MPDF*
`;

export default function ThemeDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { user, token } = useAuth();
  const themeId = params.id as string;

  const [theme, setTheme] = useState<ThemeData | null>(null);
  const [loading, setLoading] = useState(true);
  const [userRating, setUserRating] = useState<number>(0);
  const [hoverRating, setHoverRating] = useState<number>(0);
  const [showCss, setShowCss] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [ratingLoading, setRatingLoading] = useState(false);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Load theme from API
  useEffect(() => {
    async function fetchTheme() {
      try {
        const res = await fetch(`/api/themes/${themeId}`);
        if (res.ok) {
          const data = await res.json();
          setTheme(data.theme);
        }
      } catch (error) {
        console.error("Failed to fetch theme:", error);
      } finally {
        setLoading(false);
      }
    }
    fetchTheme();
  }, [themeId]);

  // Show notification helper
  const showNotification = (message: string) => {
    setNotification(message);
    setTimeout(() => setNotification(null), 3000);
  };

  // Handle rating
  const handleRate = async (rating: number) => {
    if (!user) {
      setShowAuthModal(true);
      return;
    }
    
    setRatingLoading(true);
    try {
      const res = await fetch(`/api/themes/${themeId}/rate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ rating }),
      });
      
      if (res.ok) {
        setUserRating(rating);
        showNotification(`Rated ${rating} star${rating > 1 ? "s" : ""}!`);
        // Refresh theme to get updated rating
        const themeRes = await fetch(`/api/themes/${themeId}`);
        if (themeRes.ok) {
          const data = await themeRes.json();
          setTheme(data.theme);
        }
      }
    } catch (error) {
      console.error("Failed to rate:", error);
      showNotification("Failed to rate theme");
    } finally {
      setRatingLoading(false);
    }
  };

  // Handle share
  const handleShare = async () => {
    if (!theme) return;
    const url = `${window.location.origin}/themes/${theme._id}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: theme.name,
          text: theme.description,
          url,
        });
        showNotification("Shared successfully!");
      } catch {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(url);
      showNotification("Link copied to clipboard!");
    }
  };

  // Handle copy/fork theme
  const handleCopyTheme = async () => {
    if (!user) {
      setShowAuthModal(true);
      return;
    }
    
    try {
      const res = await fetch(`/api/themes/${themeId}/copy`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      
      if (res.ok) {
        const data = await res.json();
        showNotification("Theme copied to your collection!");
        router.push(`/themes/${data.theme._id}`);
      }
    } catch (error) {
      console.error("Failed to copy theme:", error);
      showNotification("Failed to copy theme");
    }
  };

  // Handle use theme
  const handleUseTheme = async () => {
    if (!theme) return;
    // Track download
    try {
      await fetch(`/api/themes/${themeId}/download`, { method: "POST" });
    } catch {
      // Ignore tracking errors
    }
    router.push(`/editor?theme=${theme._id}`);
  };

  const updatePreview = useCallback(() => {
    if (!iframeRef.current || !theme) return;

    const htmlContent = marked.parse(PREVIEW_CONTENT);
    const fullHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Space+Grotesk:wght@400;500;600;700&family=Poppins:wght@400;500;600;700;800&family=Fira+Code:wght@400;500&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
${PDF_BASE_CSS}
${theme.css}
  </style>
</head>
<body>
  ${htmlContent}
</body>
</html>
    `;

    const iframe = iframeRef.current;
    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (doc) {
      doc.open();
      doc.write(fullHtml);
      doc.close();
    }
  }, [theme]);

  useEffect(() => {
    updatePreview();
  }, [updatePreview]);

  if (loading) {
    return (
      <div className="min-h-screen bg-zinc-950 text-white">
        <Navigation />
        <div className="pt-32 text-center">
          <div className="animate-spin w-8 h-8 border-2 border-violet-500 border-t-transparent rounded-full mx-auto" />
          <p className="text-zinc-400 mt-4">Loading theme...</p>
        </div>
      </div>
    );
  }

  if (!theme) {
    return (
      <div className="min-h-screen bg-zinc-950 text-white">
        <Navigation />
        <div className="pt-32 text-center">
          <h1 className="text-2xl font-bold mb-4">Theme not found</h1>
          <Link href="/themes" className="text-violet-400 hover:text-violet-300">
            ← Back to Theme Store
          </Link>
        </div>
      </div>
    );
  }

  const validation = validateTheme(theme.css);
  const averageRating = theme.ratingCount > 0 ? theme.ratingSum / theme.ratingCount : 0;

  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <Navigation />

      {/* Header */}
      <section className="pt-24 pb-8 border-b border-zinc-800">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex items-center gap-2 text-sm text-zinc-500 mb-6">
            <Link href="/themes" className="hover:text-white transition-colors">
              Theme Store
            </Link>
            <span>/</span>
            <span className="text-zinc-300">{theme.name}</span>
          </div>

          <div className="flex flex-col lg:flex-row gap-8">
            {/* Theme Info */}
            <div className="flex-1">
              <div className="flex items-start gap-4 mb-4">
                <div
                  className="w-16 h-16 rounded-xl shrink-0"
                  style={{ background: theme.preview }}
                />
                <div>
                  <h1 className="text-3xl font-bold mb-2">{theme.name}</h1>
                  <p className="text-zinc-400">{theme.description}</p>
                </div>
              </div>

              {/* Author */}
              <div className="flex items-center gap-3 mb-6">
                <div className="w-8 h-8 bg-gradient-to-br from-violet-500 to-purple-500 rounded-full flex items-center justify-center font-medium">
                  {theme.author.username[0]}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{theme.author.username}</span>
                    {theme.author.verified && (
                      <svg
                        className="w-4 h-4 text-blue-400"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                      >
                        <path
                          fillRule="evenodd"
                          d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                          clipRule="evenodd"
                        />
                      </svg>
                    )}
                  </div>
                  <span className="text-sm text-zinc-500">Theme Creator</span>
                </div>
              </div>

              {/* Stats */}
              <div className="flex items-center gap-6 text-sm">
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-1 text-yellow-400">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <svg
                        key={star}
                        className={cn(
                          "w-5 h-5",
                          star <= Math.round(averageRating)
                            ? "fill-current"
                            : "fill-zinc-700"
                        )}
                        viewBox="0 0 20 20"
                      >
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                      </svg>
                    ))}
                  </div>
                  <span className="text-white font-medium">{averageRating.toFixed(1)}</span>
                  <span className="text-zinc-500">({theme.ratingCount} reviews)</span>
                </div>
                <span className="text-zinc-600">•</span>
                <span className="text-zinc-400">
                  {theme.downloads.toLocaleString()} downloads
                </span>
              </div>
            </div>

            {/* Actions */}
            <div className="lg:w-72 space-y-4">
              <Button
                className="w-full bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 h-12 text-base"
                onClick={handleUseTheme}
              >
                <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                </svg>
                Use This Theme
              </Button>
              <Button
                variant="outline"
                className="w-full h-12 text-base bg-zinc-800 border-zinc-700 hover:bg-zinc-700 text-white"
                onClick={handleCopyTheme}
              >
                <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy to My Themes
              </Button>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  className="flex-1 h-12 text-base bg-zinc-800 border-zinc-700 hover:bg-zinc-700 text-white"
                  onClick={() => setShowCss(!showCss)}
                >
                  <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                  {showCss ? "Hide" : "CSS"}
                </Button>
                <Button
                  variant="outline"
                  className="flex-1 h-12 text-base bg-zinc-800 border-zinc-700 hover:bg-zinc-700 text-white"
                  onClick={handleShare}
                >
                  <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                  </svg>
                  Share
                </Button>
              </div>
            </div>
          </div>

          {/* Tags */}
          <div className="flex flex-wrap gap-2 mt-6">
            {theme.tags.map((tag) => (
              <Link
                key={tag}
                href={`/themes?tag=${tag}`}
                className="px-3 py-1 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-sm rounded-full capitalize transition-colors"
              >
                {tag}
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Preview */}
          <div className="lg:col-span-2 space-y-6">
            <div>
              <h2 className="text-xl font-semibold mb-4">Live Preview</h2>
              <div className="bg-zinc-200 rounded-xl p-4 overflow-hidden">
                <iframe
                  ref={iframeRef}
                  title="Theme Preview"
                  className="w-full h-[600px] bg-white rounded-lg shadow-lg"
                  sandbox="allow-same-origin"
                />
              </div>
            </div>

            {/* CSS View */}
            {showCss && (
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-xl font-semibold">Theme CSS</h2>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => navigator.clipboard.writeText(theme.css)}
                    className="text-zinc-400 hover:text-white"
                  >
                    <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    Copy
                  </Button>
                </div>
                <pre className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 overflow-x-auto text-sm text-zinc-300 max-h-96">
                  <code>{theme.css}</code>
                </pre>
              </div>
            )}

            {/* Description */}
            {theme.longDescription && (
              <div>
                <h2 className="text-xl font-semibold mb-4">About This Theme</h2>
                <p className="text-zinc-400 leading-relaxed">
                  {theme.longDescription}
                </p>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Validation Status */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h3 className="font-semibold mb-4 flex items-center gap-2">
                <svg className="w-5 h-5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Validation Status
              </h3>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-zinc-400">Schema Compliance</span>
                  <span
                    className={cn(
                      "px-2 py-0.5 rounded text-sm font-medium",
                      validation.valid
                        ? "bg-emerald-500/10 text-emerald-400"
                        : "bg-amber-500/10 text-amber-400"
                    )}
                  >
                    {validation.valid ? "Valid" : "Warnings"}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-zinc-400">Coverage</span>
                  <span className="text-white font-medium">
                    {validation.coverage.percentage}%
                  </span>
                </div>
                <div className="w-full bg-zinc-800 rounded-full h-2">
                  <div
                    className="bg-emerald-500 h-2 rounded-full transition-all"
                    style={{ width: `${validation.coverage.percentage}%` }}
                  />
                </div>
              </div>
            </div>

            {/* Rate This Theme */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h3 className="font-semibold mb-4">Rate This Theme</h3>
              <div className="flex items-center gap-1 mb-3">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    type="button"
                    key={star}
                    disabled={ratingLoading}
                    onMouseEnter={() => setHoverRating(star)}
                    onMouseLeave={() => setHoverRating(0)}
                    onClick={() => handleRate(star)}
                    className="p-1 transition-transform hover:scale-110 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <svg
                      className={cn(
                        "w-8 h-8 transition-colors",
                        star <= (hoverRating || userRating)
                          ? "fill-yellow-400 text-yellow-400"
                          : "fill-zinc-700 text-zinc-700"
                      )}
                      viewBox="0 0 20 20"
                    >
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  </button>
                ))}
              </div>
              {!user && (
                <p className="text-sm text-zinc-500">
                  Sign in to rate this theme
                </p>
              )}
              {userRating > 0 && (
                <p className="text-sm text-emerald-400">
                  Thanks for rating! You gave {userRating} star{userRating > 1 && "s"}.
                </p>
              )}
            </div>

            {/* Share */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h3 className="font-semibold mb-4">Share This Theme</h3>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="flex-1 bg-zinc-800 border-zinc-700 hover:bg-zinc-700 text-white"
                  onClick={handleShare}
                >
                  <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy Link
                </Button>
              </div>
            </div>

            {/* Theme Info */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h3 className="font-semibold mb-4">Theme Info</h3>
              <dl className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <dt className="text-zinc-500">Created</dt>
                  <dd className="text-zinc-300">
                    {new Date(theme.createdAt).toLocaleDateString()}
                  </dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-zinc-500">Downloads</dt>
                  <dd className="text-zinc-300">{theme.downloads}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-zinc-500">Selectors</dt>
                  <dd className="text-zinc-300">{validation.coverage.found}</dd>
                </div>
              </dl>
            </div>
          </div>
        </div>
      </div>

      {/* Notification Toast */}
      {notification && (
        <div className="fixed bottom-6 right-6 bg-zinc-800 border border-zinc-700 text-white px-4 py-3 rounded-lg shadow-lg animate-in slide-in-from-bottom-2 fade-in duration-200 z-50">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            {notification}
          </div>
        </div>
      )}

      {/* Auth Modal */}
      <AuthModal
        isOpen={showAuthModal}
        onClose={() => setShowAuthModal(false)}
      />
    </div>
  );
}
